import type { Medication } from './medicationTypes'

export const INITIAL_MEDICATIONS: Medication[] = [
  { id: 1, commercialName: 'Milteforan', activeIngredient: 'Miltefosina', indications: ['Leishmaniose Visceral Canina'], dosage: '2 mg/kg', doseMgKg: 2, frequency: 'SID (uma vez ao dia)', route: 'Oral', concentration: '30 mg/mL', concentrationMgMl: 30, contraindications: ['Gestação', 'Lactação', 'Insuficiência renal grave'], notes: 'Tratamento por 28 dias consecutivos. Monitorar função renal.' },
  { id: 2, commercialName: 'Doxiciclina', activeIngredient: 'Doxiciclina', indications: ['Erliquiose', 'Leptospirose', 'Doenças respiratórias'], dosage: '10 mg/kg', doseMgKg: 10, frequency: 'BID (duas vezes ao dia)', route: 'Oral', concentration: '100 mg/comprimido', concentrationMgMl: null, contraindications: ['Gestação', 'Filhotes em fase de dentição'], notes: 'Administrar com alimento e água. Evitar associação com antiácidos.' },
  { id: 3, commercialName: 'Amoxicilina + Clavulanato', activeIngredient: 'Amoxicilina + Ácido Clavulânico', indications: ['Infecções bacterianas', 'Infecções de pele', 'Infecções urinárias'], dosage: '12,5–25 mg/kg', doseMgKg: 12.5, frequency: 'BID (duas vezes ao dia)', route: 'Oral', concentration: '250 mg/comprimido', concentrationMgMl: null, contraindications: ['Hipersensibilidade a penicilinas'], notes: 'Completar todo o período prescrito, mesmo com melhora clínica.' },
  { id: 4, commercialName: 'Itraconazol', activeIngredient: 'Itraconazol', indications: ['Esporotricose', 'Dermatofitoses', 'Infecções fúngicas'], dosage: '5–10 mg/kg', doseMgKg: 5, frequency: 'SID (uma vez ao dia)', route: 'Oral', concentration: '100 mg/cápsula', concentrationMgMl: null, contraindications: ['Doença hepática grave', 'Gestação'], notes: 'Monitorar enzimas hepáticas em tratamentos prolongados.' },
  { id: 5, commercialName: 'Prednisona', activeIngredient: 'Prednisona', indications: ['Processos inflamatórios', 'Doenças autoimunes', 'Alergias'], dosage: '0,5–2 mg/kg', doseMgKg: 0.5, frequency: 'SID (uma vez ao dia)', route: 'Oral', concentration: '20 mg/comprimido', concentrationMgMl: null, contraindications: ['Infecções fúngicas sistêmicas', 'Úlcera gastrointestinal'], notes: 'A retirada deve ser gradual após tratamentos prolongados.' },
]
