import type { Zoonosis } from './zoonosisTypes'

export const INITIAL_ZOONOSES: Zoonosis[] = [
  { id: 1, name: 'Leishmaniose Visceral', agent: 'Leishmania infantum', risk: 'Alto', prevalence: 'Alta', hosts: ['Cães', 'Gatos (raro)', 'Raposas'], transmission: 'Picada de flebotomíneos infectados.', symptoms: ['Emagrecimento', 'Lesões de pele', 'Crescimento das unhas', 'Apatia'], diagnostics: ['Sorologia', 'PCR', 'Exame parasitológico'], prevention: ['Coleira repelente', 'Controle do vetor', 'Limpeza ambiental'] },
  { id: 2, name: 'Raiva', agent: 'Vírus da raiva (Lyssavirus)', risk: 'Alto', prevalence: 'Média', hosts: ['Cães', 'Gatos', 'Morcegos', 'Mamíferos silvestres'], transmission: 'Mordedura, arranhadura ou contato com saliva de animal infectado.', symptoms: ['Mudança de comportamento', 'Agressividade ou paralisia', 'Salivação excessiva', 'Dificuldade para engolir', 'Convulsões', 'Hidrofobia'], diagnostics: ['Histórico de exposição', 'Sinais clínicos característicos', 'Imunofluorescência direta (post-mortem)', 'Isolamento viral'], prevention: ['Vacinação antirrábica anual', 'Evitar contato com animais silvestres', 'Controle de morcegos', 'Notificação de casos suspeitos'] },
  { id: 3, name: 'Leptospirose', agent: 'Leptospira interrogans', risk: 'Alto', prevalence: 'Alta', hosts: ['Cães', 'Roedores', 'Bovinos', 'Suínos'], transmission: 'Contato com urina, água ou solo contaminados.', symptoms: ['Febre', 'Vômitos', 'Icterícia', 'Insuficiência renal'], diagnostics: ['Sorologia MAT', 'PCR', 'Hemograma e bioquímico'], prevention: ['Vacinação', 'Controle de roedores', 'Evitar água contaminada'] },
  { id: 4, name: 'Toxoplasmose', agent: 'Toxoplasma gondii', risk: 'Médio', prevalence: 'Média', hosts: ['Gatos', 'Cães', 'Mamíferos em geral'], transmission: 'Ingestão de oocistos ou carne contaminada.', symptoms: ['Febre', 'Alterações neurológicas', 'Problemas respiratórios'], diagnostics: ['Sorologia', 'PCR'], prevention: ['Higiene de alimentos', 'Limpeza adequada de caixas de areia'] },
  { id: 5, name: 'Esporotricose', agent: 'Sporothrix brasiliensis', risk: 'Alto', prevalence: 'Alta', hosts: ['Gatos', 'Cães', 'Humanos'], transmission: 'Arranhaduras, mordidas ou contato com lesões.', symptoms: ['Lesões nodulares', 'Úlceras cutâneas', 'Secreção'], diagnostics: ['Cultura fúngica', 'Citologia'], prevention: ['Tratamento dos animais', 'Uso de luvas', 'Controle populacional de gatos'] },
  { id: 6, name: 'Brucelose Canina', agent: 'Brucella canis', risk: 'Médio', prevalence: 'Baixa', hosts: ['Cães'], transmission: 'Contato com secreções reprodutivas.', symptoms: ['Aborto', 'Infertilidade', 'Orquite'], diagnostics: ['Sorologia', 'Hemocultura', 'PCR'], prevention: ['Testagem reprodutiva', 'Isolamento de positivos'] },
  { id: 7, name: 'Giardíase', agent: 'Giardia duodenalis', risk: 'Baixo', prevalence: 'Alta', hosts: ['Cães', 'Gatos', 'Humanos'], transmission: 'Ingestão de cistos em água ou alimentos.', symptoms: ['Diarreia', 'Perda de peso', 'Desidratação'], diagnostics: ['Exame coproparasitológico', 'Teste de antígeno'], prevention: ['Água tratada', 'Higiene ambiental'] },
  { id: 8, name: 'Doença de Chagas', agent: 'Trypanosoma cruzi', risk: 'Alto', prevalence: 'Baixa', hosts: ['Cães', 'Mamíferos silvestres'], transmission: 'Contato com fezes de triatomíneos infectados.', symptoms: ['Arritmias', 'Fraqueza', 'Insuficiência cardíaca'], diagnostics: ['Sorologia', 'PCR', 'Eletrocardiograma'], prevention: ['Controle de vetores', 'Melhoria habitacional'] },
]
