import type { PatientRecord } from './recordTypes'

function escapeHtml(value: string | number) {
  return String(value).replaceAll('&', '&amp;').replaceAll('<', '&lt;').replaceAll('>', '&gt;').replaceAll('"', '&quot;').replaceAll("'", '&#039;')
}

function value(value: string, fallback = '') { return escapeHtml(value || fallback) }
function field(label: string, fieldValue = '') { return `<label>${label}<span>${value(fieldValue)}</span></label>` }
function blankRows(columns: number, count = 2) { return Array.from({ length: count }, () => `<tr>${'<td></td>'.repeat(columns)}</tr>`).join('') }

export function exportPatientRecord(patient: PatientRecord) {
  const reportWindow = window.open('', '_blank', 'width=1100,height=900')
  if (!reportWindow) return false
  const records = [...patient.records].sort((a, b) => b.date.localeCompare(a.date))
  const latest = records[0]
  const latestWeight = patient.weights.at(-1)?.weight
  const vaccines = patient.vaccines.map((item) => { const [name, date = ''] = item.split(' - '); return `<tr><td>${value(name)}</td><td>${value(date)}</td><td></td><td></td><td></td></tr>` }).join('')
  const evolution = records.map((record) => `<tr><td>${new Date(`${record.date}T12:00:00`).toLocaleDateString('pt-BR')}</td><td>${value(record.description)}</td><td>${value(record.kind)}</td><td>${value(`${record.veterinarian} - ${record.crmv}`)}</td></tr>`).join('')
  const prescriptions = latest.prescriptions.map((item) => `<tr><td>${value(item)}</td><td></td><td></td><td></td><td></td></tr>`).join('')
  const requestedExams = ['Hemograma', 'Bioquímico', 'Urina', 'Fezes', 'Radiografia', 'Ultrassonografia'].map((exam) => `<span class="check">${latest.exams.some((item) => item.includes(exam)) ? '☒' : '☐'} ${exam}</span>`).join('')

  reportWindow.document.write(`<!doctype html><html lang="pt-BR"><head><meta charset="UTF-8"><title>Ficha de prontuário - ${value(patient.dogName)}</title><style>
    *{box-sizing:border-box}@page{size:A4;margin:7mm}body{margin:0;background:#e9eeec;color:#173b38;font:10px/1.35 Arial,sans-serif}.page{width:210mm;margin:12px auto;padding:5mm;border:1.5px solid #176b65;border-radius:6px;background:white;box-shadow:0 4px 20px #0002}.title{display:grid;grid-template-columns:48px 1fr 145px;align-items:center;gap:10px;padding:0 6px 8px}.logo{width:42px;height:42px;display:grid;place-items:center;border-radius:7px;background:#075a56;color:white;font-size:23px;font-weight:bold}.title h1{margin:0;color:#07524e;font-size:21px;text-transform:uppercase}.title p{margin:1px 0 0;font-size:9px}.number{padding:7px;border:1px solid #2c7771;border-radius:6px;font-weight:bold}.number span{display:block;height:18px;margin-top:3px;border-bottom:1px solid #78908d}.grid{display:grid;grid-template-columns:repeat(6,1fr);gap:5px}.box{grid-column:span 3;margin:0;padding:7px 6px 6px;border:1px solid #27756f;border-radius:4px;break-inside:avoid}.box.third{grid-column:span 2}.box.two{grid-column:span 4}.box.full{grid-column:1/-1}.box h2{margin:-7px -6px 7px;padding:5px 7px;border-bottom:1px solid #27756f;background:#edf7f5;color:#125b56;font-size:9px;text-transform:uppercase}.fields{display:grid;grid-template-columns:1fr 1fr;gap:5px 10px}.fields.one{grid-template-columns:1fr}.fields label{display:flex;align-items:end;gap:4px;white-space:nowrap}.fields span{min-height:17px;flex:1;padding:2px;border-bottom:1px solid #8fa09d;color:#111;white-space:normal}.fields .wide{grid-column:1/-1}.line{min-height:24px;padding:3px;border-bottom:1px solid #8fa09d;color:#111}table{width:100%;border-collapse:collapse;color:#183a37;font-size:7.5px}th,td{height:21px;padding:3px;border:1px solid #aab8b6;text-align:left;vertical-align:top}th{background:#e8f4f2}.physical{display:grid;grid-template-columns:repeat(3,1fr);gap:10px}.physical>div+div{padding-left:10px;border-left:1px solid #9badaa}.checks{display:grid;grid-template-columns:1fr 1fr;gap:5px}.check{color:#172d2a}.footer{margin:6px auto 0;padding:4px;border:1px solid #27756f;border-radius:9px;text-align:center;font-size:8px;font-weight:bold;letter-spacing:2px}.actions{position:fixed;right:20px;bottom:20px;display:flex;gap:8px}.actions button{padding:10px 14px;border:0;border-radius:7px;color:white;font-weight:bold;cursor:pointer}.print{background:#287642}.close{background:#555}@media print{body{background:white}.page{width:auto;margin:0;padding:0;border:0;box-shadow:none}.actions{display:none}}@media(max-width:850px){.page{width:100%;margin:0}.grid{grid-template-columns:1fr}.box,.box.third,.box.two,.box.full{grid-column:1}.title{grid-template-columns:42px 1fr}.number{grid-column:1/-1}}
  </style></head><body><main class="page"><header class="title"><div class="logo">✚</div><div><h1>Ficha de Prontuário Animal</h1><p>Registro Clínico Veterinário - IFES Campus Santa Teresa</p></div><div class="number">Nº do prontuário<span>${String(patient.id).padStart(4, '0')}</span></div></header><div class="grid">
  <section class="box"><h2>1. Identificação do animal</h2><div class="fields">${field('Nome',patient.dogName)}${field('Espécie','Canino')}${field('Raça',patient.breed)}${field('Sexo',patient.sex)}${field('Idade',patient.age)}${field('Peso',latestWeight ? `${latestWeight} kg` : '')}${field('Microchip')}${field('Nº cadastro',String(patient.id).padStart(4,'0'))}</div></section>
  <section class="box"><h2>2. Dados do tutor</h2><div class="fields">${field('Nome',patient.tutorName)}${field('CPF')}${field('Telefone')}${field('E-mail')}<label class="wide">Endereço<span></span></label><label class="wide">Cidade/UF<span></span></label></div></section>
  <section class="box"><h2>3. Histórico clínico</h2><div class="fields one">${field('Queixa principal',latest.description)}<label>Histórico da doença<span>${value(latest.description)}</span></label>${field('Doenças anteriores',patient.previousDiseases.join(', '))}${field('Alergias',patient.allergies.join(', ')||'Nenhuma conhecida')}${field('Medicamentos em uso',latest.prescriptions.join('; '))}${field('Observações')}</div></section>
  <section class="box"><h2>4. Vacinação e prevenção</h2><table><thead><tr><th>Vacina/procedimento</th><th>Data</th><th>Dose</th><th>Próxima dose</th><th>Observações</th></tr></thead><tbody>${vaccines}${blankRows(5,1)}</tbody></table><div class="fields one" style="margin-top:5px">${field('Controle de pulgas')}${field('Controle de carrapatos')}${field('Observações')}</div></section>
  <section class="box full"><h2>5. Exame físico</h2><div class="physical"><div class="fields one">${field('Temperatura',' °C')}${field('Frequência cardíaca',' bpm')}${field('Frequência respiratória',' mpm')}${field('Mucosas')}${field('TPC',' seg')}${field('Hidratação')}</div><div class="fields one">${field('Pele e pelagem')}${field('Olhos')}${field('Ouvidos')}${field('Boca/dentes')}${field('Sistema respiratório')}${field('Sistema cardiovascular')}</div><div class="fields one">${field('Sistema gastrointestinal')}${field('Sistema urinário')}${field('Sistema reprodutivo')}${field('Sistema neurológico')}${field('Dor')}${field('Observações')}</div></div></section>
  <section class="box third"><h2>6. Exames solicitados</h2><div class="checks">${requestedExams}</div><p>Resultados/alterações encontradas:</p><div class="line">${value(latest.exams.join(', '))}</div><div class="line"></div></section>
  <section class="box third"><h2>7. Diagnóstico</h2><p>Suspeita clínica:</p><div class="line"></div><p>Diagnóstico definitivo:</p><div class="line">${value(latest.diagnosis)}</div><p>Diagnósticos diferenciais:</p><div class="line"></div></section>
  <section class="box third"><h2>8. Tratamento</h2><table><thead><tr><th>Medicamento</th><th>Dose</th><th>Via</th><th>Frequência</th><th>Duração</th></tr></thead><tbody>${prescriptions}${blankRows(5,1)}</tbody></table><p>Procedimentos realizados:</p><div class="line">${value(latest.conduct)}</div><p>Orientações ao tutor:</p><div class="line"></div></section>
  <section class="box two"><h2>9. Evolução clínica</h2><table><thead><tr><th>Data</th><th>Evolução/observações</th><th>Procedimentos</th><th>Responsável</th></tr></thead><tbody>${evolution}</tbody></table></section>
  <section class="box third"><h2>10. Retorno</h2><div class="fields one">${field('Data recomendada')}${field('Motivo')}${field('Exames para o retorno')}<label>Observações<span style="min-height:30px"></span></label></div></section>
  <section class="box"><h2>11. Alta</h2><div class="fields one">${field('Data')}${field('Condição na alta')}<label>Orientações<span style="min-height:28px"></span></label>${field('Prognóstico')}${field('Retorno necessário')}</div></section>
  <section class="box"><h2>12. Responsável pelo atendimento</h2><div class="fields one">${field('Médico(a)-veterinário(a)',latest.veterinarian)}${field('CRMV',latest.crmv)}${field('Alunos participantes',latest.students.join(', '))}${field('Assinatura/validação',latest.validatedBy)}${field('Data',new Date(`${latest.date}T12:00:00`).toLocaleDateString('pt-BR'))}</div></section>
  </div><footer class="footer">DIAGNOVETIS - CUIDAR TAMBÉM É REGISTRAR</footer></main><div class="actions"><button class="close" onclick="window.close()">Fechar</button><button class="print" onclick="window.print()">Imprimir / Salvar PDF</button></div></body></html>`)
  reportWindow.document.close()
  return true
}
